added full width underline to h2
flatiron-school/docdock pull request #5
Opened 2019-04-10 22:07 UTC by dagonyclark

2019-04-10 22:42 UTC, rrcobb reviewed
Run `yarn build-theme` then commit the changes to style.css

2019-04-10 22:42 UTC, rrcobb requested changes
(requesting changes to style.css to be committed)

2019-04-11 01:01 UTC, dagonyclark commented
OK, I think I got it this time.

2019-04-11 17:55 UTC, rrcobb approved these changes

2019-04-11 18:20 UTC, merged